import os

DISCORD_TOKEN = os.environ["DISCORD_TOKEN"]
DISCORD_STATUS = os.environ["DISCORD_STATUS"]
LAVALINK_SERVER = os.environ["LAVALINK_SERVER"]
LAVALINK_PORT = os.environ["LAVALINK_PORT"]
LAVALINK_PASSWORD = os.environ["LAVALINK_PASSWORD"]
