version: "3.1"

services:
  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:latest
    healthcheck:
      test: java HealthCheck.java || exit 1
      interval: 5s
      retries: 4
      start_period: 5s
      timeout: 10s
    restart: on-failure:3
    ports:
      - 2333:2333
    network_mode: host
    volumes:
      - ./application.yaml:/opt/Lavalink/application.yaml
      - ./logs:/opt/Lavalink/logs
      - ./HealthCheck.java:/opt/Lavalink/HealthCheck.java
    entrypoint: java -Xmx512m -jar Lavalink.jar

  squiddie:
    container_name: squiddie
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:3
    tty: true
    depends_on:
      lavalink:
        condition: service_healthy
    network_mode: host
